const express = require('express');
const crypto = require('crypto');
const { requireAuth } = require('../../core/security');
const { debitBalance, creditBalance } = require('../../core/economyService');
const { runtimeStore } = require('../../core/runtimeStore');
const router = express.Router();
const rooms = new Map();
const INITIAL_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const now = () => Date.now();
function uid(req){ return String(req.user?.uid || ''); }
function name(req){ return String(req.user?.email || req.user?.name || `Oyuncu-${uid(req).slice(0,5)}`); }
function bet(v){ return Math.max(0, Math.min(10000, Math.trunc(Number(v) || 0))); }
function id(){ return `ch_${now()}_${crypto.randomBytes(3).toString('hex')}`; }
function publicRoom(r){ return { id:r.id, roomId:r.id, status:r.status, host:r.players[0]?.name || 'Bilinmeyen', guest:r.players[1]?.name || 'Bilinmeyen', hostUid:r.players[0]?.uid || '', guestUid:r.players[1]?.uid || '', players:r.players.map(p=>({ uid:p.uid, name:p.name, color:p.color, connected:true, timeLeftMs:p.timeLeftMs })), turn:r.turn, fen:r.fen, bet:r.bet, pot:r.pot, mode:r.mode, moves:r.moves, winnerUid:r.winnerUid || '', result:r.result || '', stateVersion:r.stateVersion, createdAt:r.createdAt, updatedAt:r.updatedAt } }
function findOpen(){ return [...rooms.values()].find(r => r.status === 'waiting' && r.mode !== 'private' && r.players.length < 2); }
async function chargeBet(req, r){ if (!r.bet) return { ok:true }; return debitBalance({ uid:uid(req), amount:r.bet, reason:'chess-bet', idempotencyKey:`chess:bet:${r.id}:${uid(req)}` }); }
async function payWinner(r, winnerUid){ if (!r.bet || !winnerUid) return null; return creditBalance({ uid:winnerUid, amount:r.pot, reason:'chess-win', idempotencyKey:`chess:win:${r.id}:${winnerUid}` }); }
async function settleDraw(r){ if (!r.bet) return null; const out=[]; for (const p of r.players) out.push(await creditBalance({ uid:p.uid, amount:Math.floor(r.bet/2), reason:'chess-draw-half-refund', idempotencyKey:`chess:draw:${r.id}:${p.uid}` })); return out; }
function createRoom(req, opts={}){ const safeBet=bet(opts.bet); const r={ id:id(), status:'waiting', mode:opts.mode || (safeBet ? 'bet' : 'free'), bet:safeBet, pot:safeBet, fen:INITIAL_FEN, turn:'w', moves:[], stateVersion:1, createdAt:now(), updatedAt:now(), players:[{ uid:uid(req), name:name(req), color:'w', timeLeftMs:600000 }]}; rooms.set(r.id,r); return r; }
router.get('/lobby', (_req,res)=>res.json({ ok:true, rooms:[...rooms.values()].filter(r=>r.status !== 'finished').map(publicRoom) }));
router.post('/create', requireAuth, async (req,res)=>{ const r=createRoom(req,{ bet:req.body?.bet || 0, mode:req.body?.mode }); const charged=await chargeBet(req,r); if(!charged.ok){rooms.delete(r.id); return res.status(409).json(charged);} res.json({ ok:true, room:publicRoom(r), balance:charged.balance }); });
router.post('/join', requireAuth, async (req,res)=>{ let r=req.body?.roomId ? rooms.get(String(req.body.roomId)) : findOpen(); if(!r) r=createRoom(req,{ bet:req.body?.bet || 0 }); if(r.players.some(p=>p.uid===uid(req))) return res.json({ ok:true, room:publicRoom(r) }); if(r.players.length>=2) return res.status(409).json({ ok:false,error:'ROOM_FULL' }); const charged=await chargeBet(req,r); if(!charged.ok) return res.status(409).json(charged); r.players.push({uid:uid(req), name:name(req), color:'b', timeLeftMs:600000}); r.pot += r.bet; r.status='playing'; r.updatedAt=now(); res.json({ ok:true, room:publicRoom(r), balance:charged.balance }); });
router.get('/state/:roomId', requireAuth, (req,res)=>{ const r=rooms.get(String(req.params.roomId)); if(!r) return res.status(404).json({ ok:false,error:'ROOM_NOT_FOUND' }); res.json({ ok:true, room:publicRoom(r) }); });
router.post('/ping', requireAuth, (req,res)=>{ const r=rooms.get(String(req.body.roomId)); if(!r) return res.status(404).json({ ok:false,error:'ROOM_NOT_FOUND' }); r.updatedAt=now(); res.json({ ok:true, room:publicRoom(r) }); });
router.post('/move', requireAuth, (req,res)=>{ const r=rooms.get(String(req.body.roomId)); if(!r) return res.status(404).json({ ok:false,error:'ROOM_NOT_FOUND' }); if(r.status!=='playing') return res.status(409).json({ ok:false,error:'ROOM_NOT_PLAYING' }); const player=r.players.find(p=>p.uid===uid(req)); if(!player) return res.status(403).json({ ok:false,error:'NOT_IN_ROOM' }); if(player.color!==r.turn) return res.status(409).json({ ok:false,error:'NOT_YOUR_TURN' }); const from=String(req.body.from||''); const to=String(req.body.to||''); if(!/^[a-h][1-8]$/.test(from)||!/^[a-h][1-8]$/.test(to)||from===to) return res.status(400).json({ ok:false,error:'INVALID_MOVE_FORMAT' }); r.moves.push({from,to,by:uid(req),at:now()}); r.turn=r.turn==='w'?'b':'w'; r.stateVersion+=1; r.updatedAt=now(); res.json({ ok:true, room:publicRoom(r) }); });
router.post('/resign', requireAuth, async (req,res)=>{ const r=rooms.get(String(req.body.roomId)); if(!r) return res.status(404).json({ok:false,error:'ROOM_NOT_FOUND'}); const loser=uid(req); const winner=r.players.find(p=>p.uid!==loser); r.status='finished'; r.result='resign'; r.winnerUid=winner?.uid||''; r.stateVersion+=1; const paid=winner?await payWinner(r,winner.uid):null; res.json({ok:true, room:publicRoom(r), balance:paid?.balance}); });
router.post('/draw', requireAuth, async (req,res)=>{ const r=rooms.get(String(req.body.roomId)); if(!r) return res.status(404).json({ok:false,error:'ROOM_NOT_FOUND'}); r.status='finished'; r.result='draw'; r.stateVersion+=1; await settleDraw(r); res.json({ok:true, room:publicRoom(r)}); });
router.post('/leave', requireAuth, async (req,res)=>{ const r=rooms.get(String(req.body.roomId)); if(!r) return res.json({ok:true}); if(r.status==='playing'){ const winner=r.players.find(p=>p.uid!==uid(req)); r.status='finished'; r.result='leave'; r.winnerUid=winner?.uid||''; if(winner) await payWinner(r,winner.uid); } else { rooms.delete(r.id); } res.json({ok:true, room:r.status?publicRoom(r):null}); });
function installSocket(io){ io.on('connection', socket=>{ socket.on('chess:join', roomId=>{ socket.join(`chess:${roomId}`); }); }); }
setInterval(()=>{ const cutoff=now()-2*60*60*1000; for(const [k,r] of rooms) if(r.updatedAt<cutoff) rooms.delete(k); },60000).unref();
module.exports={ router, installSocket, _rooms:rooms };
