const path = require('path');
const express = require('express');
const http = require('http');
const compression = require('compression');
const helmet = require('helmet');
const cors = require('cors');
const { Server } = require('socket.io');
const env = require('./server/config/env');
const { corsOptions } = require('./server/config/cors');
const { initFirebaseAdmin } = require('./server/config/firebaseAdmin');
const { apiLimiter } = require('./server/core/security');
const { routeData } = require('./server/core/smartDataRouter');
const { runtimeStore } = require('./server/core/runtimeStore');
initFirebaseAdmin();
const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: env.allowedOrigins, credentials: true } });
app.disable('x-powered-by');
app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
app.use(compression());
app.use(cors(corsOptions));
app.use(express.json({ limit: '512kb' }));
app.use(apiLimiter);
app.use(express.static(__dirname, { extensions: ['html'], maxAge: env.nodeEnv === 'production' ? '1h' : 0 }));
app.get('/healthz', (req,res)=>res.json({ ok:true, service:'playmatrix', env:env.nodeEnv, time:Date.now() }));
app.use('/api', require('./server/routes/compat.routes'));
app.use('/api', require('./server/routes/auth.routes'));
app.use('/api', require('./server/routes/user.routes'));
app.use('/api', require('./server/routes/admin.routes'));
app.use('/api', require('./server/routes/economy.routes'));
app.use('/api', require('./server/routes/notification.routes'));
app.use('/api', require('./server/routes/social.routes'));
app.use('/api', require('./server/routes/email.routes'));
app.use('/api/games/pisti', require('./server/games/pisti').router);
app.use('/api/games/chess', require('./server/games/chess').router);
app.use('/api/games/crash', require('./server/games/crash').router);
app.use('/api/games/snake', require('./server/games/snake').router);
app.use('/api/games/space', require('./server/games/space').router);
app.use('/api/games/pattern-master', require('./server/games/pattern-master').router);
app.use('/api/games/music-tiles', require('./server/games/music-tiles').router);
app.post('/api/client/error', async (req,res)=>{ runtimeStore.errors.set(`${Date.now()}_${Math.random()}`, req.body, 24*3600000); await routeData({ classification:'IMPORTANT', collection:'clientErrors', payload:req.body }); res.json({ ok:true }); });
const redirects = { '/games/crash':'/games/crash','/games/chess':'/games/chess','/games/pisti':'/games/pisti','/games/snake':'/games/snake','/games/space':'/games/space','/games/pattern-master':'/games/pattern-master' };
for (const [from,to] of Object.entries(redirects)) { app.get(from, (req,res)=>res.redirect(301,to)); app.get(`${from}.html`, (req,res)=>res.redirect(301,to)); }
io.on('connection', socket => { runtimeStore.presence.set(socket.id, { socketId: socket.id, at: Date.now() }); socket.on('presence:update', data => runtimeStore.presence.set(socket.id, { socketId: socket.id, ...data, at: Date.now() })); socket.on('matchmaking:leave', data => socket.emit('matchmaking:left', { ok:true })); socket.on('disconnect', () => runtimeStore.presence.delete(socket.id)); });
setInterval(()=>{ Object.values(runtimeStore).forEach(store => store.prune && store.prune()); }, 60_000).unref();
app.use((req,res)=>res.status(404).json({ ok:false, error:'NOT_FOUND' }));
app.use((err,req,res,next)=>{ console.error('[server:error]', err); res.status(500).json({ ok:false, error:'INTERNAL_ERROR' }); });
const port = Number(process.env.PORT || 3000);
if (require.main === module) server.listen(port, () => console.log(`[playmatrix] listening on ${port}`));
module.exports = { app, server, io };
