const path=require('path');const express=require('express');const http=require('http');const compression=require('compression');const helmet=require('helmet');const cors=require('cors');const {Server}=require('socket.io');const env=require('./server/config/env');const {corsOptions}=require('./server/config/cors');const {initFirebaseAdmin}=require('./server/config/firebaseAdmin');const {apiLimiter}=require('./server/core/security');const {routeData}=require('./server/core/smartDataRouter');const {runtimeStore}=require('./server/core/runtimeStore');
process.on('unhandledRejection',reason=>console.error('[process:unhandledRejection]',reason&&reason.stack||reason));process.on('uncaughtException',error=>console.error('[process:uncaughtException]',error&&error.stack||error));initFirebaseAdmin();
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:env.allowedOrigins,credentials:true}});app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(compression());app.use(cors(corsOptions));app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
app.use((req,res,next)=>{const started=Date.now();res.on('finish',()=>{if(res.statusCode>=400)console.error('[api:error]',JSON.stringify({method:req.method,path:req.originalUrl||req.url,status:res.statusCode,ms:Date.now()-started,requestId:req.headers['x-request-id']||null}));});next();});
app.use(apiLimiter);app.use(express.static(__dirname,{extensions:['html'],maxAge:env.nodeEnv==='production'?'1h':0,redirect:false}));app.get('/healthz',(_req,res)=>res.json({ok:true,service:'playmatrix-v7',env:env.nodeEnv,time:Date.now()}));
const {getProfile,uidFromReq,emailFromReq}=require('./server/core/economyService');app.get('/api/me',async(req,res)=>{const uid=uidFromReq(req);const profile=await getProfile(uid,{email:emailFromReq(req)});res.json({ok:true,user:profile,profile,balance:profile.balance,accountLevel:profile.accountLevel,accountLevelProgressPct:profile.accountLevelProgressPct,progression:profile.progression});});app.get('/api/leaderboard',async(_req,res)=>{const users=['guest','u1','demo'].map((uid,i)=>({uid,username:i===0?'Misafir':uid,avatar:'',balance:50000-i*5000,xp:String(i*250),accountXp:String(i*250)})).map(u=>{const {applyProgression}=require('./server/core/economyService');return applyProgression(u)});res.json({ok:true,items:users});});app.use('/api',require('./server/routes/market.routes'));app.use('/api',require('./server/routes/wheel.routes'));app.use('/api',require('./server/routes/promo.routes'));app.use('/api',require('./server/routes/support.routes'));app.use('/api',require('./server/routes/compat.routes'));app.use('/api',require('./server/routes/auth.routes'));app.use('/api',require('./server/routes/user.routes'));app.use('/api',require('./server/routes/admin.routes'));app.use('/api',require('./server/routes/economy.routes'));app.use('/api',require('./server/routes/notification.routes'));app.use('/api',require('./server/routes/social.routes'));app.use('/api',require('./server/routes/email.routes'));
app.use('/api/games/crash',require('./server/games/crash').router);app.use('/api/games/chess',require('./server/games/chess').router);app.use('/api/games/pisti',require('./server/games/pisti').router);app.use('/api/games/pattern-master',require('./server/games/pattern-master').router);app.use('/api/games/space-pro',require('./server/games/space-pro').router);app.use('/api/games/snake-pro',require('./server/games/snake-pro').router);
app.use('/api/games/space',require('./server/games/space-pro').router);app.use('/api/games/snake',require('./server/games/snake-pro').router);
async function captureClientError(req,res){const payload={...(req.body||{}),path:req.body?.path||req.headers.referer||'',userAgent:req.headers['user-agent']||'',at:Date.now()};runtimeStore.errors.set(`${Date.now()}_${Math.random()}`,payload,24*3600000);console.error('[frontend-report]',JSON.stringify({type:payload.type||'client',message:String(payload.message||'').slice(0,400),path:String(payload.path||'').slice(0,240),source:String(payload.source||'').slice(0,240),line:payload.line||null}));await routeData({classification:'IMPORTANT',collection:'clientErrors',payload});res.status(202).json({ok:true});}
app.post('/api/client/error',captureClientError);app.post('/api/client-errors',captureClientError);
const gamePages=Object.freeze({'crash':'crash','chess':'chess','satranc':'chess','satranç':'chess','pisti':'pisti','pişti':'pisti','pattern-master':'pattern-master','patternmaster':'pattern-master','space-pro':'space-pro','space':'space-pro','spacepro':'space-pro','snake-pro':'snake-pro','snake':'snake-pro','snakepro':'snake-pro'});function sendGamePage(slug,res,next){const safe=gamePages[String(slug||'').toLowerCase()]||'';if(!safe)return next();res.setHeader('Cache-Control','no-store, max-age=0');return res.sendFile(path.join(__dirname,'games',safe,'index.html'));}app.get('/games/:slug',(req,res,next)=>sendGamePage(req.params.slug,res,next));app.get('/games/:slug/',(req,res,next)=>sendGamePage(req.params.slug,res,next));
const aliases={'/Online Oyunlar/Crash.html':'/games/crash','/Online Oyunlar/Pisti.html':'/games/pisti','/Online Oyunlar/Satranc.html':'/games/chess','/Klasik Oyunlar/SnakePro.html':'/games/snake-pro','/Klasik Oyunlar/SpacePro.html':'/games/space-pro','/Klasik Oyunlar/PatternMaster.html':'/games/pattern-master','/games/space':'/games/space-pro','/games/snake':'/games/snake-pro'};for(const[from,to]of Object.entries(aliases))app.get(from,(_req,res)=>res.redirect(302,to));
io.on('connection',socket=>{runtimeStore.presence.set(socket.id,{socketId:socket.id,at:Date.now()});socket.on('presence:update',data=>runtimeStore.presence.set(socket.id,{socketId:socket.id,...data,at:Date.now()}));socket.on('client:error',data=>{console.error('[socket:client:error]',JSON.stringify({socketId:socket.id,data}));runtimeStore.errors.set(`socket_${Date.now()}_${socket.id}`,data||{},24*3600000);});socket.on('matchmaking:join',data=>socket.emit('matchmaking:status',{ok:true,game:data?.game||'unknown',mode:'http-api',message:'Satranç ve Pişti hızlı eşleşmesi /api/games/{game}/quick üzerinden çalışır.'}));socket.on('game:invite',data=>socket.emit('game:invite:ack',{ok:true,data}));socket.on('disconnect',()=>runtimeStore.presence.delete(socket.id));});
setInterval(()=>{Object.values(runtimeStore).forEach(store=>store.prune&&store.prune());},60000).unref();
app.use((req,res)=>res.status(404).json({ok:false,error:'NOT_FOUND'}));app.use((err,req,res,next)=>{console.error('[server:error]',JSON.stringify({message:err?.message||String(err),stack:err?.stack||'',path:req.originalUrl||req.url,method:req.method}));res.status(500).json({ok:false,error:'INTERNAL_ERROR'});});
const port=Number(process.env.PORT||3000);if(require.main===module)server.listen(port,()=>console.log(`[playmatrix] listening on ${port}`));module.exports={app,server,io};
