const express = require('express');
const crypto = require('crypto');
const env = require('../config/env');
const { requireAuth, strictLimiter } = require('../core/security');
const { initFirebaseAdmin } = require('../config/firebaseAdmin');
const { runtimeStore } = require('../core/runtimeStore');
const { getProgression } = require('../core/progressionService');
const { runOnce } = require('../core/idempotencyService');
const pistiGame = require('../games/pisti');
const chessGame = require('../games/chess');
const crashGame = require('../games/crash');
const router = express.Router();
const DEFAULT_AVATAR = 'data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%20128%20128%27%3E%3Crect%20width%3D%27128%27%20height%3D%27128%27%20rx%3D%2728%27%20fill%3D%27%23111827%27%2F%3E%3Ccircle%20cx%3D%2764%27%20cy%3D%2750%27%20r%3D%2724%27%20fill%3D%27%23f59e0b%27%2F%3E%3Cpath%20d%3D%27M26%20108c8-18%2024-28%2038-28s30%2010%2038%2028%27%20fill%3D%27%23fbbf24%27%2F%3E%3Ctext%20x%3D%2764%27%20y%3D%27118%27%20text-anchor%3D%27middle%27%20font-family%3D%27Arial%27%20font-size%3D%2716%27%20font-weight%3D%27700%27%20fill%3D%27%23fff%27%3EPM%3C%2Ftext%3E%3C%2Fsvg%3E';
const pistiRooms = new Map();
const chessRooms = new Map();
let activeCrashRound = null;
const now = () => Date.now();
const s = (v, max = 200) => String(v || '').trim().slice(0, max);
const sanitizeText = (v, max = 500) => s(v, max).replace(/[<>]/g, '');
const uidOf = (req) => s(req.user?.uid || req.headers['x-playmatrix-user'] || req.body?.uid || req.query?.uid || '', 128);
const fb = () => initFirebaseAdmin();
function addProgression(profile) { const xp = Number(profile.accountXp ?? profile.xp ?? profile.accountLevelScore ?? 0) || 0; const progression = getProgression(xp); return { ...profile, xp: progression.currentXp, accountXp: progression.currentXp, accountLevel: progression.accountLevel, level: progression.accountLevel, accountLevelProgressPct: progression.accountLevelProgressPct, progression }; }
function defaultProfile(req, uid) { const email = s(req.user?.email || req.user?.firebase?.identities?.email?.[0] || '', 160); const username = s(req.user?.name || (email ? email.split('@')[0] : `Oyuncu-${String(uid).slice(0,5)}`), 32); return addProgression({ uid, email, username, fullName: username, displayName: username, avatar: DEFAULT_AVATAR, selectedFrame: 0, balance: 0, xp: 0, accountXp: 0, monthlyActiveScore: 0, totalRounds: 0, createdAt: now(), lastLogin: now(), lastSeen: now(), gameStats: { total: { rounds: 0, wins: 0, losses: 0, winRatePct: 0 }, chess: {}, pisti: {}, crash: {}, classic: {} } }); }
async function readProfile(req, uid = uidOf(req)) { let profile = defaultProfile(req, uid || 'guest'); const { db } = fb(); if (db && uid) { const snap = await db.collection('users').doc(uid).get(); if (snap.exists) profile = { ...profile, ...snap.data(), uid }; else await db.collection('users').doc(uid).set(profile, { merge: true }).catch(() => null); } return addProgression(profile); }
async function writeProfile(uid, patch) { const { db } = fb(); if (db && uid) await db.collection('users').doc(uid).set({ ...patch, updatedAt: now() }, { merge: true }); }
async function addBalance(uid, amount, reason, key) { const { db, admin } = fb(); const safeAmount = Math.floor(Number(amount) || 0); if (!db || !admin || !uid || !safeAmount) return { ok: true, amount: safeAmount, reason, firestore: false }; return runOnce({ key, db, execute: async () => { await db.collection('users').doc(uid).set({ balance: admin.firestore.FieldValue.increment(safeAmount), updatedAt: now() }, { merge: true }); await db.collection('audit').doc(`economy_${crypto.randomUUID()}`).set({ uid, amount: safeAmount, reason, at: now() }, { merge: true }); return { ok: true, amount: safeAmount, reason }; } }); }
function runtimePayload() { return { ok: true, runtime: { version: 6, environment: env.nodeEnv, publicBaseUrl: env.publicBaseUrl, canonicalOrigin: env.canonicalOrigin, apiBase: env.publicApiBase || env.publicBackendOrigin, expectedFirebaseProjectId: env.firebase.publicConfig.projectId, firebase: env.firebase.publicConfig, firebaseReady: true, source: 'render-env-contract' }, apiBase: env.publicApiBase || env.publicBackendOrigin, canonicalOrigin: env.canonicalOrigin, firebase: env.firebase.publicConfig }; }
async function leaderboardProfiles() { const { db } = fb(); if (!db) return []; try { const snap = await db.collection('users').orderBy('accountXp', 'desc').limit(25).get(); return snap.docs.map(d => ({ uid: d.id, ...d.data() })); } catch (_) { try { const snap = await db.collection('users').limit(25).get(); return snap.docs.map(d => ({ uid: d.id, ...d.data() })); } catch { return []; } } }
function lbItems(list, metric) { return list.map((raw, i) => { const p = addProgression(raw); return { uid: p.uid || `guest_${i}`, username: p.username || p.displayName || 'Oyuncu', avatar: p.avatar || DEFAULT_AVATAR, selectedFrame: Number(p.selectedFrame || 0) || 0, accountXp: Number(p.accountXp || 0), accountLevel: Number(p.accountLevel || 1), monthlyActiveScore: Number(p.monthlyActiveScore || 0), leaderboard: { rank: i + 1, metricKey: metric === 'activity' ? 'monthlyActiveScore' : 'accountXp', metricLabel: metric === 'activity' ? 'Aylık Aktiflik' : 'Hesap XP', metricValue: metric === 'activity' ? Number(p.monthlyActiveScore || 0) : Number(p.accountXp || 0) } }; }); }
router.get('/public/runtime-config', (_req, res) => res.json(runtimePayload()));
router.get('/healthz', (_req, res) => res.json({ ok: true, service: 'playmatrix-api', at: now() }));
router.post('/auth/resolve-login', strictLimiter, async (req, res) => { const id = s(req.body?.identifier || req.body?.email || req.body?.username, 160); if (!id) return res.status(400).json({ ok: false, error: 'IDENTIFIER_REQUIRED' }); if (id.includes('@')) return res.json({ ok: true, email: id.toLowerCase() }); const { db } = fb(); if (!db) return res.status(404).json({ ok: false, error: 'USER_NOT_FOUND' }); const q = await db.collection('users').where('usernameLower', '==', id.toLowerCase()).limit(1).get(); if (q.empty || !q.docs[0].data().email) return res.status(404).json({ ok: false, error: 'USER_NOT_FOUND' }); res.json({ ok: true, email: q.docs[0].data().email }); });
router.post('/auth/session/create', requireAuth, async (req, res) => { const token = crypto.randomBytes(32).toString('hex'); const uid = uidOf(req); runtimeStore.temporary.set(`session:${token}`, { uid, at: now() }, 30 * 86400000); res.json({ ok: true, sessionToken: token, session: { token, expiresAt: now() + 30 * 86400000 }, user: await readProfile(req, uid).catch(() => ({ uid })) }); });
router.post('/auth/session/logout', (req, res) => { const token = s(req.headers['x-session-token'] || req.body?.sessionToken, 100); if (token) runtimeStore.temporary.delete(`session:${token}`); res.json({ ok: true }); });
router.get('/auth/session/status', (req, res) => { const token = s(req.headers['x-session-token'] || req.query?.sessionToken, 100); res.json({ ok: true, active: !!(token && runtimeStore.temporary.get(`session:${token}`)) }); });
router.get('/me', requireAuth, async (req, res) => res.json({ ok: true, user: await readProfile(req) }));
router.post('/me/activity/heartbeat', requireAuth, async (req, res) => { const uid = uidOf(req); runtimeStore.presence.set(uid, { uid, status: 'online', activity: s(req.body?.activity, 40), at: now() }, 180000); res.json({ ok: true, at: now() }); });
router.post('/me/showcase', requireAuth, async (req, res) => { const uid = uidOf(req); const showcase = { title: s(req.body?.title, 60), bio: sanitizeText(req.body?.bio || '', 180), updatedAt: now() }; await writeProfile(uid, { showcase }); res.json({ ok: true, showcase }); });
router.get('/user-stats/:uid', requireAuth, async (req, res) => res.json({ ok: true, data: await readProfile(req, s(req.params.uid, 128)) }));
router.get('/leaderboard', async (req, res) => { const profiles = await leaderboardProfiles(); const fallback = profiles.length ? profiles : [addProgression({ uid: 'playmatrix', username: 'PlayMatrix', accountXp: 0, avatar: DEFAULT_AVATAR })]; const byLevel = [...fallback].sort((a,b)=>Number(b.accountXp||b.xp||0)-Number(a.accountXp||a.xp||0)); const byActivity = [...fallback].sort((a,b)=>Number(b.monthlyActiveScore||0)-Number(a.monthlyActiveScore||0)); res.json({ ok: true, generatedAt: now(), tabs: { level: { label: 'En Yüksek Hesap Seviyesi', metricKey: 'accountXp', items: lbItems(byLevel, 'level') }, activity: { label: 'En Çok Aktif Oyuncular', metricKey: 'monthlyActiveScore', items: lbItems(byActivity, 'activity') } } }); });
router.get('/check-username', requireAuth, async (req, res) => { const username = s(req.query.username, 32); if (username.length < 3) return res.json({ ok: true, available: false }); const { db } = fb(); if (!db) return res.json({ ok: true, available: true }); const snap = await db.collection('users').where('usernameLower', '==', username.toLowerCase()).limit(1).get(); res.json({ ok: true, available: snap.empty }); });
router.post('/profile/update', requireAuth, async (req, res) => { const uid = uidOf(req); const patch = { fullName: s(req.body?.fullName, 80), username: s(req.body?.username, 32), avatar: s(req.body?.avatar, 1000), selectedFrame: Math.max(0, Math.min(18, Math.floor(Number(req.body?.selectedFrame) || 0))) }; if (patch.username) patch.usernameLower = patch.username.toLowerCase(); Object.keys(patch).forEach(k => { if (patch[k] === '' && k !== 'selectedFrame') delete patch[k]; }); await writeProfile(uid, patch); res.json({ ok: true, user: await readProfile(req, uid) }); });
router.get('/notifications', requireAuth, (_req, res) => res.json({ ok: true, items: [], unread: 0, summary: { total: 0, unread: 0 } }));
router.post('/notifications/read', requireAuth, (_req, res) => res.json({ ok: true }));
router.post('/notifications/read-all', requireAuth, (_req, res) => res.json({ ok: true }));
router.post('/wheel/spin', requireAuth, strictLimiter, async (req, res) => { const prizes = [2500,5000,7500,12500,20000,25000,30000,50000]; const uid = uidOf(req); const index = crypto.randomInt(0, prizes.length); const prize = prizes[index]; await addBalance(uid, prize, 'daily-wheel', `wheel:${uid}:${new Date().toISOString().slice(0,10)}`); res.json({ ok: true, prize, amount: prize, index }); });
router.post('/bonus/claim', requireAuth, strictLimiter, async (req, res) => { const code = s(req.body?.code, 64).toUpperCase(); if (!code) return res.status(400).json({ ok: false, error: 'PROMO_CODE_REQUIRED' }); const uid = uidOf(req); const amount = /^PLAY|PM|PROMO/.test(code) ? 10000 : 2500; await addBalance(uid, amount, `promo:${code}`, `promo:${uid}:${code}`); res.json({ ok: true, code, amount }); });
router.get('/referral/link', requireAuth, (req, res) => { const uid = uidOf(req); const code = `PM-${uid.slice(0,8).toUpperCase()}`; res.json({ ok: true, code, link: `${env.publicBaseUrl}/?ref=${encodeURIComponent(code)}` }); });
router.post('/referral/claim', requireAuth, (_req, res) => res.json({ ok: true, claimed: false }));
router.post('/support/receipt', requireAuth, (req, res) => { const id = `sup_${crypto.randomUUID()}`; runtimeStore.temporary.set(id, { id, uid: uidOf(req), subject: sanitizeText(req.body?.subject || '', 100), note: sanitizeText(req.body?.note || req.body?.message || '', 800), at: now() }, 14 * 86400000); res.json({ ok: true, id, status: 'open' }); });
router.post('/support/callback', requireAuth, (_req, res) => res.json({ ok: true }));
router.get('/friends/list', requireAuth, (_req, res) => res.json({ ok: true, lists: { accepted: [], incoming: [], outgoing: [] }, counts: { accepted: 0, incoming: 0, outgoing: 0, online: 0 } }));
router.post('/friends/request', requireAuth, (req, res) => res.json({ ok: true, message: 'Arkadaşlık isteği işlendi.', request: { targetUid: s(req.body?.targetUid || req.body?.target, 128), at: now() } }));
router.post('/friends/respond', requireAuth, (_req, res) => res.json({ ok: true }));
router.post('/friends/remove', requireAuth, (_req, res) => res.json({ ok: true }));
router.get('/social-center/summary', requireAuth, async (req, res) => res.json({ ok: true, me: await readProfile(req), chatPolicy: { memoryOnly: true }, counts: { friends: 0, incoming: 0, notifications: 0 }, features: { globalChat: true, localChat: true, dm: true, presence: 'memory' } }));
router.get('/activity-pass', requireAuth, (_req, res) => res.json({ ok: true, active: true, claimable: false }));
router.post('/activity-pass/claim', requireAuth, (_req, res) => res.json({ ok: true, claimed: false }));
router.get('/chat/settings', requireAuth, (req, res) => res.json({ ok: true, mine: {}, theirs: {}, targetUid: s(req.query.targetUid, 128) }));
router.get('/chat/direct/list', requireAuth, (_req, res) => res.json({ ok: true, items: [] }));
router.get('/chat/direct/search', requireAuth, (_req, res) => res.json({ ok: true, items: [], nextCursor: '' }));
router.get('/chat/direct/history', requireAuth, (req, res) => { const key = [uidOf(req), s(req.query.targetUid || req.query.peerUid, 128)].sort().join('_'); res.json({ ok: true, items: runtimeStore.temporary.get(`dm:${key}`) || [], nextCursor: '' }); });
router.get('/chat/direct/unread-summary', requireAuth, (_req, res) => res.json({ ok: true, byPeer: {}, total: 0 }));
['edit','delete','archive','unarchive'].forEach(a => router.post(`/chat/direct/${a}`, requireAuth, (_req, res) => res.json({ ok: true })));
['block','unblock','mute','unmute','report'].forEach(a => router.post(`/chat/${a}`, requireAuth, (_req, res) => res.json({ ok: true })));
function publicPisti(room, uid) { return room ? { ...room, hand: uid ? (room.hands?.[uid] || []) : [], hands: undefined } : null; }
function newPisti(uid, opp = 'bot') { const room = pistiGame.createRoom([{ uid }, { uid: opp }]); pistiRooms.set(room.roomId, room); return room; }
router.get('/pisti-online/lobby', requireAuth, (req, res) => res.json({ ok: true, rooms: [...pistiRooms.values()].map(r => publicPisti(r, uidOf(req))) }));
router.get('/pisti-online/resume', requireAuth, (req, res) => { const uid = uidOf(req); res.json({ ok: true, room: publicPisti([...pistiRooms.values()].find(r => r.players.includes(uid)), uid) }); });
router.post('/pisti-online/play-open', requireAuth, (req, res) => { const uid = uidOf(req); const room = newPisti(uid); res.json({ ok: true, roomId: room.roomId, room: publicPisti(room, uid) }); });
router.post('/pisti-online/create-private', requireAuth, (req, res) => { const uid = uidOf(req); const room = newPisti(uid); res.json({ ok: true, roomId: room.roomId, code: room.roomId.slice(-6).toUpperCase(), room: publicPisti(room, uid) }); });
router.post('/pisti-online/join', requireAuth, (req, res) => { const uid = uidOf(req); const roomId = s(req.body?.roomId || req.body?.code, 100); const room = pistiRooms.get(roomId) || newPisti(uid); if (!room.players.includes(uid)) room.players[1] = uid; res.json({ ok: true, roomId: room.roomId, room: publicPisti(room, uid) }); });
router.post('/pisti-online/ping', requireAuth, (req, res) => res.json({ ok: true, room: publicPisti(pistiRooms.get(s(req.body?.roomId, 100)), uidOf(req)) }));
router.get('/pisti-online/state/:id', requireAuth, (req, res) => res.json({ ok: true, room: publicPisti(pistiRooms.get(s(req.params.id, 100)), uidOf(req)) }));
router.post('/pisti-online/play', requireAuth, (req, res) => { try { const uid = uidOf(req); const room = pistiRooms.get(s(req.body?.roomId, 100)); if (!room) return res.status(404).json({ ok: false, error: 'ROOM_NOT_FOUND' }); const out = pistiGame.play(room, uid, s(req.body?.cardId || req.body?.card, 20)); res.json({ ok: true, ...out, room: publicPisti(room, uid) }); } catch (e) { res.status(400).json({ ok: false, error: e.message }); } });
router.post('/pisti-online/leave', requireAuth, (req, res) => { pistiRooms.delete(s(req.body?.roomId, 100)); res.json({ ok: true }); });
function newChess(uid, black = 'bot') { const room = chessGame.createRoom([{ uid }, { uid: black }]); chessRooms.set(room.roomId, room); return room; }
router.get('/chess/lobby', requireAuth, (_req, res) => res.json({ ok: true, rooms: [...chessRooms.values()] }));
router.get('/chess/resume', requireAuth, (req, res) => { const uid = uidOf(req); res.json({ ok: true, room: [...chessRooms.values()].find(r => Object.values(r.players || {}).includes(uid)) || null }); });
router.post('/chess/create', requireAuth, (req, res) => { const room = newChess(uidOf(req)); res.json({ ok: true, roomId: room.roomId, room }); });
router.post('/chess/join', requireAuth, (req, res) => { const roomId = s(req.body?.roomId, 100); const room = chessRooms.get(roomId) || newChess(uidOf(req)); if (room.players.black === 'bot') room.players.black = uidOf(req); res.json({ ok: true, roomId: room.roomId, room }); });
router.get('/chess/state/:id', requireAuth, (req, res) => res.json({ ok: true, room: chessRooms.get(req.params.id) || null }));
router.post('/chess/ping', requireAuth, (req, res) => res.json({ ok: true, room: chessRooms.get(s(req.body?.roomId, 100)) || null }));
router.post('/chess/move', requireAuth, (req, res) => { const room = chessRooms.get(s(req.body?.roomId, 100)); if (!room) return res.status(404).json({ ok:false, error:'ROOM_NOT_FOUND' }); try { const ChessLib = require('chess.js'); const Chess = ChessLib.Chess || ChessLib; const game = new Chess(room.fen); const move = game.move(req.body.move || { from: req.body.from, to: req.body.to, promotion: req.body.promotion || 'q' }); if (!move) return res.status(400).json({ ok:false, error:'ILLEGAL_MOVE' }); room.fen = game.fen(); room.pgn = game.pgn(); room.turn = game.turn(); res.json({ ok:true, move, room }); } catch (e) { res.status(400).json({ ok:false, error:e.message }); } });
router.post('/chess/resign', requireAuth, (req, res) => { const room = chessRooms.get(s(req.body?.roomId, 100)); if (room) room.status = 'resigned'; res.json({ ok: true, room }); });
router.post('/chess/leave', requireAuth, (_req, res) => res.json({ ok: true }));
function newCrash() { const seed = crypto.randomBytes(32).toString('hex'); const hash = crypto.createHash('sha256').update(seed).digest('hex'); activeCrashRound = { id: `cr_${now()}`, hash, seed, crashAt: crashGame.multiplierFromSeed(seed), state: 'open', bets: {}, createdAt: now() }; runtimeStore.rooms.set(activeCrashRound.id, activeCrashRound, 600000); return activeCrashRound; }
router.get('/crash/resume', requireAuth, (_req, res) => res.json({ ok: true, round: activeCrashRound || newCrash() }));
router.get('/crash/active-bets', requireAuth, (req, res) => { const uid = uidOf(req); const round = activeCrashRound || newCrash(); res.json({ ok: true, bets: round.bets?.[uid] ? [round.bets[uid]] : [], round }); });
router.get('/crash/history', (_req, res) => res.json({ ok: true, items: runtimeStore.temporary.get('crash:history') || [] }));
router.post('/crash/bet', requireAuth, (req, res) => { const uid = uidOf(req); const amount = Math.max(1, Math.floor(Number(req.body?.amount || req.body?.bet || 1))); const round = activeCrashRound || newCrash(); if (round.bets[uid]) return res.status(409).json({ ok: false, error: 'BET_EXISTS' }); round.bets[uid] = { uid, amount, roundId: round.id, at: now() }; res.json({ ok: true, roundId: round.id, round, bet: round.bets[uid] }); });
router.post('/crash/cashout', requireAuth, async (req, res) => { const uid = uidOf(req); const round = activeCrashRound || newCrash(); const bet = round.bets[uid]; if (!bet) return res.status(400).json({ ok: false, error: 'BET_NOT_FOUND' }); const multiplier = Math.max(1, Number(req.body?.multiplier || req.body?.at || 1)); if (multiplier >= round.crashAt) return res.status(400).json({ ok: false, error: 'CRASHED' }); const win = Math.floor(bet.amount * multiplier); bet.cashout = multiplier; bet.win = win; await addBalance(uid, win, 'crash-cashout', `crash:${uid}:${round.id}`); res.json({ ok: true, win, amount: win, multiplier, round }); });

router.get('/chat/policy', requireAuth, (_req, res) => res.json({ ok: true, policy: { storage: 'memory', lobbyRetentionDays: 7, directRetentionDays: 14, presence: 'memory-only' } }));
router.get('/support/meta', requireAuth, (_req, res) => res.json({ ok: true, categories: ['Hesap', 'Oyun', 'Ödeme', 'Teknik'], channels: ['ticket', 'callback'], memoryOnlyLogs: true }));
router.post('/support/tickets', requireAuth, (req, res) => { const id = `ticket_${crypto.randomUUID()}`; const ticket = { id, uid: uidOf(req), subject: sanitizeText(req.body?.subject || 'Destek', 120), message: sanitizeText(req.body?.message || req.body?.note || '', 1000), status: 'open', at: now() }; runtimeStore.temporary.set(id, ticket, 14 * 86400000); console.info('[support:ticket]', JSON.stringify({ id, uid: ticket.uid, subject: ticket.subject })); res.status(201).json({ ok: true, ticket }); });
router.get('/support/tickets', requireAuth, (req, res) => { const uid = uidOf(req); const tickets = runtimeStore.temporary.values().filter(x => x && x.id && String(x.id).startsWith('ticket_') && x.uid === uid); res.json({ ok: true, items: tickets }); });
router.get('/rewards/center', requireAuth, (_req, res) => res.json({ ok: true, dailyWheel: true, promo: true, notifications: { receiptDays: 30 }, claimable: [] }));
router.get('/rewards/catalog', requireAuth, (_req, res) => res.json({ ok: true, items: [{ id: 'daily-wheel', title: 'Günlük Çark' }, { id: 'promo', title: 'Promo Kod' }] }));
router.get('/matches/history', requireAuth, (_req, res) => res.json({ ok: true, items: [], nextCursor: '' }));
router.get('/achievements', requireAuth, (_req, res) => res.json({ ok: true, items: [] }));
router.get('/missions', requireAuth, (_req, res) => res.json({ ok: true, items: [] }));
router.get('/platform/control', requireAuth, (_req, res) => res.json({ ok: true, maintenance: false, gamesEnabled: true }));
router.get('/me/live-session', requireAuth, (req, res) => res.json({ ok: true, session: runtimeStore.presence.get(uidOf(req)) || null }));
router.get('/me/match-history', requireAuth, (_req, res) => res.json({ ok: true, items: [] }));
router.post('/classic/submit', requireAuth, async (req, res) => { const game = s(req.body?.game || req.body?.gameType || 'classic', 40); const score = Math.max(0, Math.floor(Number(req.body?.score) || 0)); const uid = uidOf(req); const runId = s(req.body?.runId || `${game}_${now()}`, 120); const { db } = fb(); const result = await runOnce({ key: `classic:${game}:${uid}:${runId}`, db, execute: async () => ({ game, score, reward: 0 }) }); res.json({ ok: true, game, score, ...result }); });
router.post('/update', requireAuth, async (req, res) => { const uid = uidOf(req); const patch = { fullName: s(req.body?.fullName, 80), username: s(req.body?.username, 32), avatar: s(req.body?.avatar, 1000), selectedFrame: Math.max(0, Math.min(18, Math.floor(Number(req.body?.selectedFrame) || 0))) }; if (patch.username) patch.usernameLower = patch.username.toLowerCase(); Object.keys(patch).forEach(k => { if (patch[k] === '' && k !== 'selectedFrame') delete patch[k]; }); await writeProfile(uid, patch); res.json({ ok: true, user: await readProfile(req, uid) }); });
router.post('/email/update/request-code', requireAuth, (req, res) => { const uid = uidOf(req); const id = `email_code_${uid}_${crypto.randomUUID()}`; runtimeStore.temporary.set(id, { uid, email: s(req.body?.email || req.body?.newEmail, 160), at: now(), used: false }, 15 * 60 * 1000); console.info('[email:update:code]', JSON.stringify({ uid, emailMasked: String(req.body?.email || req.body?.newEmail || '').replace(/(^.).*(@.*$)/, '$1***$2') })); res.json({ ok: true, codeSent: true, expiresInSec: 900, token: id }); });
router.post('/email/update/verify-code', requireAuth, async (req, res) => { const uid = uidOf(req); const token = s(req.body?.token, 160); const item = runtimeStore.temporary.get(token); if (!item || item.uid !== uid || item.used) return res.status(400).json({ ok: false, error: 'INVALID_OR_EXPIRED_CODE' }); item.used = true; await writeProfile(uid, { email: item.email, emailVerified: true }); res.json({ ok: true, email: item.email }); });

module.exports = router;
