const API = () => (window.__PM_API__?.buildUrl ? '' : (window.__PLAYMATRIX_API_URL__ || ''));
const KEY='pm_admin_matrix_key'; const SESSION='pm_session_token';
function $(id){return document.getElementById(id)}
function clean(v){return String(v||'').trim()}
function getSession(){try{return sessionStorage.getItem(SESSION)||localStorage.getItem(SESSION)||''}catch{return''}}
function setSession(t){if(!t)return; try{sessionStorage.setItem(SESSION,t);localStorage.setItem(SESSION,t)}catch{}}
function getKey(){try{return sessionStorage.getItem(KEY)||''}catch{return''}}
function setKey(k){try{sessionStorage.setItem(KEY,k||'')}catch{}}
function clearKey(){try{sessionStorage.removeItem(KEY)}catch{}}
async function request(path, opt={}){ if(window.__PM_API__?.ensureApiBase) await window.__PM_API__.ensureApiBase().catch(()=>null); const headers=new Headers(opt.headers||{}); if(opt.body && !headers.has('Content-Type')) headers.set('Content-Type','application/json'); const s=getSession(); const k=getKey(); if(s)headers.set('x-session-token',s); if(k)headers.set('x-admin-client-key',k); const url=window.__PM_API__?.buildUrl?window.__PM_API__.buildUrl(path):(API()+path); const r=await fetch(url,{credentials:'include',cache:'no-store',...opt,headers}); const j=await r.json().catch(()=>({})); if(!r.ok||j.ok===false) throw new Error(j.error||`HTTP ${r.status}`); if(j.sessionToken||j.session?.token)setSession(j.sessionToken||j.session.token); if(j.clientKey)setKey(j.clientKey); return j; }
function status(id,msg,kind=''){const el=$(id); if(el){el.textContent=msg||'';el.className='status '+kind}}
function step(n){$('stepProgress').dataset.step=String(n); document.querySelectorAll('.gate-step').forEach(x=>x.classList.toggle('is-active',Number(x.dataset.step)===n));}
function matrix(){const c=$('matrixCanvas'); if(!c)return; const ctx=c.getContext('2d'); let w,h,cols=[]; const chars='01ABCDEFGHIJKLMNOPQRSTUVWXYZ#%&@*+-='; function resize(){w=c.width=innerWidth*devicePixelRatio;h=c.height=innerHeight*devicePixelRatio;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';cols=Array.from({length:Math.ceil(w/18)},()=>Math.random()*h)} function frame(){ctx.fillStyle='rgba(1,7,16,.12)';ctx.fillRect(0,0,w,h);ctx.font='16px monospace';ctx.fillStyle='rgba(44,255,130,.72)';cols.forEach((y,i)=>{ctx.fillText(chars[Math.random()*chars.length|0],i*18,y);cols[i]=y>h?0:y+18});requestAnimationFrame(frame)} resize(); addEventListener('resize',resize); frame()}
async function detect(){status('emailStatus','Yönetici kimliği kontrol ediliyor...'); try{const out=await request('/api/auth/admin/matrix/identity'); if(out.user?.email){$('adminEmail').value=out.user.email; status('emailStatus','Yönetici e-postası doğrulandı.','is-ok'); step(2); return;} throw new Error('ADMIN_IDENTITY_MISSING')}catch(e){status('emailStatus',e.message||'Yönetici oturumu algılanamadı. Önce ana sayfada giriş yap.','is-error')}}
async function verifyPass(){try{status('passwordStatus','Şifre doğrulanıyor...'); const out=await request('/api/auth/admin/matrix/step-password',{method:'POST',body:JSON.stringify({ticket:window.__ticket,password:$('adminPassword').value})}); window.__ticket=out.ticket; status('passwordStatus','İkinci faktör doğru.','is-ok'); step(3)}catch(e){status('passwordStatus',e.message,'is-error')}}
async function verifyName(){try{status('nameStatus','Son doğrulama yapılıyor...'); const out=await request('/api/auth/admin/matrix/step-name',{method:'POST',body:JSON.stringify({ticket:window.__ticket,adminName:$('adminName').value})}); setKey(out.clientKey); status('nameStatus','Admin oturumu hazır.','is-ok'); step(4); setTimeout(showDash,500)}catch(e){status('nameStatus',e.message,'is-error')}}
async function startGate(){try{const st=await request('/api/auth/admin/matrix/status'); if(st.authenticated){if(st.clientKey)setKey(st.clientKey);return showDash()}}catch{} try{const out=await request('/api/auth/admin/matrix/step-email',{method:'POST',body:JSON.stringify({email:''})}); window.__ticket=out.ticket; if(out.email)$('adminEmail').value=out.email; status('emailStatus','Yönetici e-postası doğrulandı.','is-ok'); step(2)}catch{detect()}}
function card(label,value){return `<article class="summary-pill"><span>${label}</span><strong>${value}</strong></article>`}
async function showDash(){ $('adminGate').hidden=true; $('adminDashboard').hidden=false; await loadDash(); }
async function loadDash(){ const [sum,users,games,logs,promos]=await Promise.all([request('/api/admin/summary').catch(()=>({metrics:{}})),request('/api/admin/users').catch(()=>({users:[]})),request('/api/admin/games').catch(()=>({games:[]})),request('/api/admin/runtime-logs').catch(()=>({logs:[]})),request('/api/admin/promos').catch(()=>({promos:[]}))]); const m=sum.metrics||{}; $('metricGrid').innerHTML=[card('Kullanıcı',m.users||0),card('Ban',m.banned||0),card('Toplam MC',m.totalBalance||0),card('Runtime Log',m.runtimeLogs||0)].join(''); $('userRows').innerHTML=(users.users||[]).map(u=>`<tr><td>${u.uid}</td><td>${u.username||u.email||'-'}</td><td>${Number(u.balance||0).toLocaleString('tr-TR')}</td><td>${u.accountLevel||1}</td></tr>`).join('')||'<tr><td colspan="4">Kullanıcı bulunamadı</td></tr>'; $('gameCards').innerHTML=(games.games||[]).map(g=>`<div class="game-admin-card"><b>${g.title}</b><span>${g.status}</span><small>${g.backend}</small></div>`).join(''); $('logRows').innerHTML=(logs.logs||[]).slice(-50).reverse().map(l=>`<tr><td>${new Date(l.at||Date.now()).toLocaleTimeString('tr-TR')}</td><td>${l.event||l.type||'-'}</td><td>${JSON.stringify(l).slice(0,160)}</td></tr>`).join(''); $('promoRows').innerHTML=(promos.promos||[]).map(p=>`<tr><td>${p.code||p.id}</td><td>${p.amount}</td><td>${p.maxClaims||p.usageLimit||'-'}</td></tr>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{matrix(); startGate(); $('retryEmail')?.addEventListener('click',detect); $('adminPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')verifyPass()}); $('retryPassword')?.addEventListener('click',()=>{$('adminPassword').value='';}); $('adminName')?.addEventListener('keydown',e=>{if(e.key==='Enter')verifyName()}); $('retryName')?.addEventListener('click',()=>{$('adminName').value='';}); $('dashboardRefreshBtn')?.addEventListener('click',loadDash); $('dashboardLogoutBtn')?.addEventListener('click',async()=>{try{await request('/api/auth/admin/matrix/logout',{method:'POST'})}catch{} clearKey(); location.reload();}); $('balanceBtn')?.addEventListener('click',async()=>{try{await request('/api/admin/users/balance',{method:'POST',body:JSON.stringify({uid:$('targetUid').value,amount:$('balanceAmount').value,reason:'admin-panel'})});status('userOpStatus','Bakiye güncellendi','is-ok');loadDash()}catch(e){status('userOpStatus',e.message,'is-error')}}); $('banBtn')?.addEventListener('click',async()=>{try{await request('/api/admin/users/ban',{method:'POST',body:JSON.stringify({uid:$('targetUid').value,reason:$('banReason').value})});status('userOpStatus','Ban güncellendi','is-ok');loadDash()}catch(e){status('userOpStatus',e.message,'is-error')}}); $('emailBtn')?.addEventListener('click',async()=>{try{await request('/api/admin/users/email',{method:'POST',body:JSON.stringify({uid:$('targetUid').value,email:$('newEmail').value})});status('userOpStatus','E-posta senkronlandı','is-ok')}catch(e){status('userOpStatus',e.message,'is-error')}}); $('promoBtn')?.addEventListener('click',async()=>{await request('/api/admin/promos',{method:'POST',body:JSON.stringify({code:$('promoCode').value,amount:$('promoAmount').value,maxClaims:$('promoLimit').value})});loadDash()}); $('cleanupDryBtn')?.addEventListener('click',()=>request('/api/admin/cleanup/firestore',{method:'POST',body:JSON.stringify({dryRun:true})}).then(loadDash)); });
