(function(){
  const $=id=>document.getElementById(id);let stage=1,ticket='',sessionToken='',clientKey='',email='';
  const api=async(path,opts={})=>{const headers={'Content-Type':'application/json',...(opts.headers||{})};if(sessionToken)headers['x-session-token']=sessionToken;if(clientKey)headers['x-admin-client-key']=clientKey;const r=await fetch('/api'+path,{credentials:'include',cache:'no-store',...opts,headers,body:opts.body&&typeof opts.body!=='string'?JSON.stringify(opts.body):opts.body});const p=await r.json().catch(()=>({ok:false,error:'BAD_JSON'}));if(!r.ok||p.ok===false)throw new Error(p.error||`HTTP_${r.status}`);return p;};
  function err(m=''){$('authError').textContent=m}function setStep(n){stage=n;document.querySelectorAll('.steps i').forEach((e,i)=>e.classList.toggle('on',i<n));$('stepPill').textContent='ADIM '+n;}
  async function identity(){try{err('');setStep(1);const p=await api('/auth/admin/matrix/identity');email=p.user?.email||'';$('adminInput').type='text';$('adminInput').value=email;$('adminInput').placeholder='Yönetici e-postası';$('fieldLabel').textContent='ALGILANAN YÖNETİCİ E-POSTASI';$('authTitle').textContent='YÖNETİCİ HESABI DOĞRULANIYOR';}catch(e){err(e.message||'AUTH_REQUIRED')}}
  async function next(){try{err('');if(stage===1){const p=await api('/auth/admin/matrix/step-email',{method:'POST',body:{email:$('adminInput').value||email}});ticket=p.ticket;setStep(2);$('adminInput').value='';$('adminInput').type='password';$('adminInput').placeholder='İkinci güvenlik şifresi';$('fieldLabel').textContent='İKİNCİ FAKTÖR';$('authTitle').textContent='GÜVENLİK ŞİFRESİ DOĞRULANIYOR';return}if(stage===2){const p=await api('/auth/admin/matrix/step-password',{method:'POST',body:{ticket,password:$('adminInput').value}});ticket=p.ticket;setStep(3);$('adminInput').value='';$('adminInput').type='text';$('adminInput').placeholder='Üçüncü doğrulama adı';$('fieldLabel').textContent='ÜÇÜNCÜ FAKTÖR';$('authTitle').textContent='SON ADIM DOĞRULANIYOR';return}if(stage===3){const p=await api('/auth/admin/matrix/step-name',{method:'POST',body:{ticket,adminName:$('adminInput').value}});sessionToken=p.sessionToken;clientKey=p.clientKey;localStorage.setItem('pm_session_token',sessionToken);localStorage.setItem('pm_admin_client_key',clientKey);setStep(4);$('authCard').classList.add('hidden');$('dashboard').classList.remove('hidden');await dashboard();}}catch(e){err(e.message)}}
  async function dashboard(){const [summary,market,risk,support,logs]=await Promise.allSettled([api('/admin/summary'),api('/market/catalog'),api('/games/crash/risk-table'),api('/admin/support/messages'),api('/admin/runtime-logs')]);$('usersCount').textContent=summary.value?.users?.total||summary.value?.summary?.users||'Aktif';$('marketCount').textContent=(market.value?.items||[]).length+' ürün';$('riskCount').textContent=(risk.value?.risk||[]).length+' aralık';$('supportCount').textContent=(support.value?.messages||[]).length+' mesaj';$('logCount').textContent=(logs.value?.logs||[]).length+' log';$('marketList').innerHTML=(market.value?.items||[]).map(x=>`<div class="row"><b>${x.name}</b><span>${Number(x.price||0).toLocaleString('tr-TR')} MC</span></div>`).join('');$('riskList').innerHTML=(risk.value?.risk||[]).map(x=>`<div class="row"><b>${x.min}x – ${x.max}x</b><span>Ağırlık ${x.weight}</span></div>`).join('');$('runtimeLogs').textContent=JSON.stringify(logs.value?.logs||[],null,2)}
  $('primaryBtn').onclick=next;$('retryBtn').onclick=identity;$('logoutBtn').onclick=()=>{localStorage.removeItem('pm_session_token');location.reload()};identity();
})();
